---
title: Categories of research
subtitle: 
author:
- name: admin

date: '2019-08-01'

slug: []
categories:
  
tags:
  - areas of interest
  - scope of research
  - dss

output:
  blogdown::html_page:
    toc: false
    toc_depth: 4

featured: no
projects: [ialsa]
image: 
  caption: ''
  focal_point: "Center"
  preview_only: no

summary: 30-50 words
abstract: 200-300 words

url_code: ""
url_dataset: ""
url_pdf: ""
url_poster: ""
url_project: ""
url_slides: ""
url_source: ""
url_video: ""

publication_types:
- "0"
---
<!-- # Publication type. -->
<!-- # Legend: -->
<!-- # 0 = Uncategorized -->
<!-- # 1 = Conference proceedings -->
<!-- # 2 = Journal -->
<!-- # 3 = Work in progress -->
<!-- # 4 = Technical report -->
<!-- # 5 = Book -->
<!-- # 6 = Book chapter -->
# Health Informatics
- [Target Information Architecture][tia] 
- [Clinical Context Coding Scheme][cccs] (Halifax, May 2019)
- [Blueprints for Learning][blueprints] (Vancouver, March 2018)

# Data Access & Disclosure Control
- [Real-world data de-identification of linked EHR][reboot] (Victoria, 2019)
- [Suppress-for-release][spr]

[tia]:http://ken.rbind.io/post/2019-07-11-target-information-architecture/
[cccs]:http://andriy.rbind.io/publication/idpln-2018-banff-clinical-context-coding-scheme/
[blueprints]:https://dss-ialh.rbind.io/post/2018-03-08-blueprints-for-learning/poster.jpg
[reboot]:http://ken.rbind.io/post/2019-07-16-data-de-identification/
[spr]:http://andriy.rbind.io/publication/koval-2019-suppress-for-release/


# Public Health
- Suppress-for-release
- Canadian Chronic Disease Surveillance System (Lisa Lix)
  - [PopDataBC webinar](https://www.popdata.bc.ca/events/etu/PPDS_Webinars_2019_Jan9)
  - https://github.com/IHACRU/analytic-environment-ccdss
-  [Florida Health Charts](http://www.flhealthcharts.com/charts/default.aspx)  
  - GLS Suicide Prevention programs ([github](https://github.com/dss-hmi/suicide-prevention-2019))
- Substance Use and Recidivism (https://github.com/dss-hmi/drug-recedivism-2019)  

# Mental Health & Substance Use
- [Severity and Burden of Mental Health](https://drive.google.com/open?id=1iLFZxXhB7a86hK_wkhy4WIl9aMtyPX71) (May 2018, Montreal)

# Statistical Learning
- [Estimating Underreported Cases of Depression](https://matthew-parker.rbind.io/post/2018-01-26-population-abundance/) (BC Chronic Disease Dashboard)

# Reproducible Research
- [When notebooks are not enough](http://andriy.rbind.io/talk/2018-10-31-when-notebooks-are-not-enough/) - on structure of reproducible evidence

# Functional Graphing
- [Visualizing Logistic Regression](http://andriy.rbind.io/talk/2018-11-01-visualizing-logistic-regression/) - what functional graphs empower you to do. 


